[project]
name = "lab02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "debugpy>=1.8.13",
    "matplotlib>=3.10.1",
    "panadas>=0.2",
    "pandas>=2.2.3",
]
